### ISSUE TITLE
Welcome back :)

### ISSUE THREAD

**Issue by notoco** [heppen-dev/plugin.video.tvpgo#1]
No...

**Comment by jestemWesolyRomek** [comment]
Nic nie rozumiem. Powiadomienie dostałem ale wejść nie mogę, pokazuje 404. Tu jakieś coś inne, Dupa123 pisze, jaja jakieś. To która teraz wersja jest do pobrania, czym to się różni od tego co było na zips.ovh/heppen?

**Comment by jestemWesolyRomek** [comment]
Kija w dupie123?? Nie kumam. Znalazłem wersję z wyższym numerkiem 1.3.7 i ona rozwiązła mój problem, bo nie muszę pliku przenosić na telewizor tylko z kodi poszła instalka.

**Comment by heppen-dev** [comment]
> Znalazłem wersję z wyższym numerkiem 1.3.7 i ona rozwiązła mój problem

Mogę podbić na 2.0.0 jeśli to dla ciebie takie ważne XD

**Comment by notoco** [comment]
> Które lepsze 1.3.7, czy twoje, czym się różnią? Pogubiłem się trochę.

To dwie zupełnie inne i odrębne wtyczki. Owszem nazwę mają tę samą, co może rodzić pewne problemy. Krótko mówiąc - wtyczka od heppena to w pełni działająca wersja, autorska. Wtyczka od kpl to także w pełni działająca wersja, ale oparta na troszkę innych zasadach i zbudowana w oparciu o libkę. Z której korzystać? Z tej z której ci wygodniej. Przymusu nie ma :)
